#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p GPU-shared
#SBATCH -t 10:00:00
#SBATCH --gres=gpu:1

source ~/.bashrc
conda activate csc791

cd /jet/home/bpark1/$USER/csc791-025/proj3

python3 proj3.py hpo TPE
python3 proj3.py hpo Evolution
python3 proj3.py hpo Hyperband

