#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p rome
#SBATCH -t 24:00:00

nvidia-smi
source ~/.bashrc
conda activate csc791
cd /home/bcpark/csc791-025/proj2


python3 proj2.py --train     # train DNNs
python3 proj2.py --quantize  # quantize DNNs
python3 proj2.py --figures   # plot figures for report
python3 proj2.py --benchmark # benchmark normal vs. quantize DNNs