#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p GPU-shared
#SBATCH -t 24:00:00
#SBATCH --gres=gpu:1

source ~/.bashrc

export TVM_NUM_THREADS=8

conda activate csc791
cd /jet/home/bpark1/csc791-025/proj4
python3 proj4.py

# tvmc compile --target "llvm" --input-shapes "data:[1,3,224,224]" --output resnet50-v2-7-tvm.tar resnet50-v2-7.onnx
# tvmc run --inputs imagenet_cat.npz --output predictions.npz resnet50-v2-7-tvm.tar

# tvmc run --inputs imagenet_cat.npz --output predictions.npz resnet50-v2-7-tvm.tar




# # FINAL

# tvmc compile --target "llvm" --input-shapes "data:[1,3,224,224]" --output resnet18-tvm.tar resnet18.onnx
# tvmc compile --target "llvm" --input-shapes "data:[1,3,224,224]" --output resnet18-kd-tvm.tar resnet18_kd.onnx




# mkdir resnet18
# tar -xvf resnet18-tvm.tar -C resnet18

# mkdir resnet18-kd
# tar -xvf resnet18-kd-tvm.tar -C resnet18-kd


# time tvmc run --inputs imagenet_cat.npz --output resnet18-predictions.npz resnet18-tvm.tar
# time tvmc run --inputs imagenet_cat.npz --output resnet18-kd-predictions.npz resnet18-kd-tvm.tar
