#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p GPU-shared
#SBATCH -t 48:00:00
#SBATCH --gres=gpu:4

nvidia-smi
export MASTER_ADDR=$(scontrol show hostname ${SLURM_NODELIST} | head -n 1)
source ~/.bashrc
conda activate csc791
cd /jet/home/bpark1/csc791-025/proj4
python3 proj4.py