#!/bin/bash
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -p GPU-shared
#SBATCH -t 48:00:00
#SBATCH --gres=gpu:1

nvidia-smi
source ~/.bashrc
conda activate csc791
cd /jet/home/bpark1/csc791-025/proj4
python3 proj4.py
export TVM_NUM_THREADS=8

mkdir tvm_models

tvmc compile --target "llvm" --input-shapes "data:[1,3,28,28]" --output tvm_models/resnet101-tvm.tar onnx_models/resnet101.onnx
tvmc compile --target "llvm" --input-shapes "data:[1,3,28,28]" --output tvm_models/resnet18-kd-tvm.tar onnx_models/resnet18_kd.onnx

mkdir tvm_models/resnet101
tar -xvf tvm_models/resnet101-tvm.tar -C tvm_models/resnet101

mkdir tvm_models/resnet18-kd
tar -xvf tvm_models/resnet18-kd-tvm.tar -C tvm_models/resnet18-kd

time tvmc run --inputs cifar10.npz --output resnet18-predictions.npz onnx_models/resnet18-tvm.tar
time tvmc run --inputs cifar10.npz --output resnet18-kd-predictions.npz onnx_models/resnet18-kd-tvm.tar
