name: Discord Notifications

on:
  push:
    branches:
    - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: GIGACHAD
        DISCORD_AVATAR: https://melmagazine.com/wp-content/uploads/2021/01/66f-1.jpg
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: 'A new commit has been pushed to ${GITHUB_REF##*/}! Giga Chad Approved!'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
